### ISSUE TITLE
Site map?

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/elo#10]
Can we establish a site map for where to take the project?

For example,
- /
  - /l/_ladder.slug_/
    - /l/_ladder.slug_/matches/
      - /l/_ladder.slug_/matches/_match.id_/
    - /l/_ladder.slug_/settings/
  - /u/profile/_user.username_/
    - /u/profile/_user.username_/matches/
    - /u/profile/_user.username_/ladders/
  - /u/messages/
    - /u/messages/challenges/
    - /u/messages/matches/
  - /u/settings/

**Comment by GordonsBeard** [comment]
Yes, I will expand upon this later but ``user.username`` is something I'm worried about using. Perhaps we can give users the ability to change their username, or something. I'd like to avoid using userIDs for identifying urls.

**Comment by GordonsBeard** [comment]
We'll use the Wiki for this.
