### ISSUE TITLE
Forfeits not resulting in a loss

### ISSUE THREAD

**Issue by GordonsBeard** [GordonsBeard/elo#13]
1. User 1 (with up arrow) challenges User 2 (with up arrow)
   ![image](https://cloud.githubusercontent.com/assets/4015791/6418550/d52d45e4-be6a-11e4-80be-b6a4d77d6b1c.png)
2. User 2 goes to messages > open challenges.
3. User 2 Forfeits the match.
   ![image](https://cloud.githubusercontent.com/assets/4015791/6418543/bd63bf1a-be6a-11e4-8be9-07a499ce6ed9.png)

Expected: After the forfeit we should see the ranks swap.
Actual: No ranks or arrows swap, users are left unchanged:
![image](https://cloud.githubusercontent.com/assets/4015791/6418560/edaa0634-be6a-11e4-9695-8cc4f64ff45a.png)

**Comment by LanaCoyote** [comment]
Yeah, it won't generate a match when a user forfeits, and `adjust_rank` is only called when a match is saved.

**Comment by GordonsBeard** [comment]
This is a bug then, a user forfeit should result in a loss. If you are on the ladder you basically have no rights to decline a match without sacrificing rank. In the future there might be a "Postpone" function that will let you put the match off, or a "Cancel" function that will either be initiated by the user (before a timelimit is up) or the Ladder Owner.

**Comment by GordonsBeard** [comment]
Fixed a bit ago.
