### ISSUE TITLE
Rank.rank and Rank.ladder_id cannot be the same

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/elo#2]
Tried to delete a Rank object in the database and got an `IntegrityError` complaining that `rank` and `ladder_id` are not unique. This is because I tried to delete the top ranked player from the first ladder (both fields are 1).

This shouldn't work like this. The `ladder_id` should not have to be different from `rank`.

**Comment by LanaCoyote** [comment]
This seems to happen intermittently?

**Comment by GordonsBeard** [comment]
Yeah I'm going to need clear repro steps, I cannot seem to trigger this.
1. Clean Database
2. Create 2 ladders
3. Create SteamUser
4. Log in as SteamUser (should be id=2) and join the 2nd ladder.
5. Go into admin panel and attempt to delete Rank object for this player on the 2nd ladder.

This works correctly for me.
