### ISSUE TITLE
Questions about Challenges

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/elo#7]
1. When a player declines a challenge, does it count as a forfeit and therefore switch player ranks on the ladder?
2. Can players cancel challenges they've issued? If so, does it count as a forfeit? Would there be a buffer (i.e. cancel in x minutes or it counts as a forfeit)?
3. Should the ladder details page display under open challenges both challenges the player has issued as well as challenges the player has received?
4. Should cancelled challenges be outright deleted or marked as cancelled?

**Comment by GordonsBeard** [comment]
1. There is no "declining" a challenge in that you can avoid penalty. When you are on the ladder you will either accept or forfeit every match given to you. 

Outcomes of: "User 1 challenges User 2":
- User 2 accepts the challenge, Match scheduled
- User 2 declines the challenge (forfeits), win is given to User 1
- User 2 does not respond in time, challenge is forfeit, win is given to User 1
1. Player cannot cancel challenges they've issued (as designed), but the idea about canceling within x minutes seems good. Perhaps if you cancel within 5 or 10 minutes then no harm no foul. Wouldn't want to make it very long though.
2. Yes, ideally the ladder pages will show you what you've opened and what's opened against you - but you cannot have more than one challenge active on a single ladder, so this may never happen (unless I do not understand the scenario).
3. Cancelled challenges should be marked as cancelled. Ideally I want an "event log" that will keep track of what happened where, cancelled challenges would be a good metric to track to see if people were farting around too much with the system.

**Comment by LanaCoyote** [comment]
So in the case of 3, if Detective has been challenged on ladder A by func_door, can Lancey challenge Detective before he accepts func_door's challenge? If so, what happens to the challenge he turns down? Could you challenge Detective even after he accepted a challenge?

**Comment by GordonsBeard** [comment]
Detective challenges func_door in Ladder A and the challenge is created. **Until this challenge is Forfeit / Canceled / Completed** no other people may challenge Detective nor func_door on Ladder A.

Both an open challenge and/or open matches will bar BOTH those users from being challenged in that ladder.

**Comment by GordonsBeard** [comment]
With the latest commit I've added `date_issued` to `Challenge` to help deal with the case of retracting challenges if it's been a short enough time.
