### ISSUE TITLE
User Auth - OpenID - Django User

### ISSUE THREAD

**Issue by GordonsBeard** [GordonsBeard/elo#8]
Currently the only way to log in is via Steam, and I eventually want to open this up to OTHER OpenID providers such as twitter/google/etc.

The problem here lies in the code that allows someone to login. Currently it's only set up to pull information from a single OpenID provider - Steam, and because of this - it can easily pull in the expected information, like Avatar, SteamID, etc.

Internally within Django a lot of user control is based off either the players ID (primary key) or their USERNAME. The problem with USERNAME (and it's a problem within the Django database I use to test with) is that it's based off the Steam handle passed along. This causes issue because the Steam handles can have unicode (dun dun dunnn) and spaces, which the Django auth system will have a fit over.

I've modified the user logins to save a slug(SteamHandle) version of their name as the USERNAME, and this works alright - but it does requires that **any calls to a user's handle be called via: user.userprofile.handle**

**Other Problems**
- {% url 'usercontrol.messages' user.username %}
  This is creating URLs based off the user.username and NOT the user.userprofile.handle. This is correct because it stops the URL from changing a bunch (does that matter?), but it's sucky because you cannot change the username easily (can we?). A few people signed up during Halloween so their usernames are "Detective-boose" and "func_door_secret", etc.
  (Bonus problem: Currently tests are flopping out on user.username, because no UserProfile object is generated when setting up the test framework - that's a lesser issue however)
- When switching away from _solely_ Steam to any number of OpenID providers, the entire login code will need to be re-written to allow for more or less flexibility within UserProfile.

**Comment by LanaCoyote** [comment]
I intentionally made user profiles based off the slugified username field. If you wanted to update the user's slug username, you could do:

``` python
user.username = get_steam_username_slug() # Or however you do it the first time
user.save()
```

This shouldn't break any links in the database because those are all ID based. I tested this just now (renamed detective-boose to detective-moose) and it didn't break anything. The only thing that'll be broken is external links that permalink to an existing user profile. I don't recommend updating it frequently, however. Maybe a thing you can choose to do every month or something.

Just for reference, use `user.id` to lookup users programatically, `user.username` to look them up in a natural way (i.e., via url), and `user.userprofile.handle` for display **only**.

**Comment by GordonsBeard** [comment]
I don't mind a whole lot about breaking permalinks from outside of ELO (Steam lets you change your display URL to your heart's content, not caring about where it's linked from), so perhaps using `user.username` won't be an issue as long as we also keep it somewhat updated with how they are logging in*

\* Or, here is an idea I just had: Take their OpenID handle (just Steam for right now) and slugify it into a username, but then give them an option to change this username before it's forever committed to the database.

We will reserve the right to change the usernames if REALLY needed, but moving away from relying solely on `user.userprofile.handle` does get a bit annoying, as it's another call that may or may not _need_ to be created.

**Comment by LanaCoyote** [comment]
lmfao whoops that wasn't supposed to close an issue on this repo
