### ISSUE TITLE
Matches should have a One-To-One relationship with Challenges

### ISSUE THREAD

**Issue by LanaCoyote** [GordonsBeard/elo#9]
I'm assuming that every Challenge only has one Match, but wouldn't it make sense for the related Challenge on a Match to be a One-To-One relationship rather than a ForeignKey?

**Comment by GordonsBeard** [comment]
Yes it does - this is just a problem with building the framework before I realized/had all the moving parts in place.

I'm sure this level of change would require a database wipe/migration/etc. I am fine with this.
